name: Release Version

on:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
      - name: Release
        env:
          # when using the generated GITHUB-TOKEN
          # the release won't trigger a pipeline
          # https://github.com/semantic-release/github?tab=readme-ov-file#github-authentication
          GITHUB_TOKEN: ${{ secrets.PAT }}
          CI: true
        run: npx semantic-release --debug
