name: Release Version

on:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          # this ensures that the GITHUB_TOKEN gets not overridden
          persist-credentials: false
      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: "lts/*"
      - name: Release
        env:
          # when using the generated GITHUB-TOKEN
          # the release won't trigger a pipeline
          # https://github.com/semantic-release/github?tab=readme-ov-file#github-authentication
          GITHUB_TOKEN: ${{ secrets.PAT }}
        run: npx semantic-release --debug
